# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillow', '0002_auto_20160530_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='picture_sm',
            field=models.CharField(max_length=1000),
        ),
    ]
