# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillow', '0003_auto_20160531_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='picture',
            field=models.ImageField(upload_to='img'),
        ),
    ]
