# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields
import pillow.models


class Migration(migrations.Migration):

    dependencies = [
        ('pillow', '0005_auto_20160531_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture_max_size', '1366x768', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='picture_max_size',
            field=models.ImageField(upload_to=pillow.models.rename_max_size),
        ),
    ]
