# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:13
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields
import pillow.models


class Migration(migrations.Migration):

    dependencies = [
        ('pillow', '0006_auto_20160531_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='picture_max_size',
            field=image_cropping.fields.ImageCropField(upload_to=pillow.models.rename_max_size),
        ),
    ]
